version: 0.2

env:
  variables:
    ACCOUNT_ID: ${CODEBUILD_BUILD_ARN} && IFS=':' && set -- $ACCOUNT_ID && ACCOUNT_ID=$5

phases:
  build:
    commands:
      - echo ${CODEBUILD_SRC_DIR}
      - echo ${ACCOUNT_ID}